package com.example.hyperionapp;

import android.app.AlertDialog;
import android.content.DialogInterface;
import android.content.Intent;
import android.os.Bundle;
import com.google.android.material.tabs.TabLayout;
import androidx.lifecycle.Lifecycle;
import androidx.lifecycle.LifecycleObserver;
import androidx.lifecycle.OnLifecycleEvent;
import androidx.lifecycle.ViewModelProviders;
import androidx.viewpager.widget.ViewPager;
import androidx.appcompat.app.AppCompatActivity;

import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;

import com.example.hyperionapp.ui.main.SectionsPagerAdapter;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.gson.Gson;


/*
    For JSON to Object coversion:
    https://mkyong.com/java/how-do-convert-java-object-to-from-json-format-gson-api/

 */

public class MainActivity extends AppCompatActivity implements LifecycleObserver {
    /* Class to handle main UI logic, loading the user data and setting up the viewModel */
    // Declare and instantiate class constants
    private FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
    private FirebaseAuth mAuth = FirebaseAuth.getInstance();
    private String user_id = user.getUid();
    final String SYMMETRIC_ALIAS = "hyperion_symmetric_" + user_id;
    final String DATA_FILENAME = user_id + "_hyperion.enc";
    private EncryptionClass encryption = new EncryptionClass();
    Gson gson = new Gson();
    LoginActivity login = new LoginActivity();

    // Declare viewModel (used to share data between Fragments)
    private PatientDetails patientModel;


    // TODO: Update the data (apart from session_shared) from the status FirebaseFirestore
    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        // Check if user is logged in
        login.isAuthenticated(MainActivity.this, user, false);
        // Grab the incoming intent in order to display the right fragment
        Intent intent = getIntent();
        // viewpager_position tells the Activity which Fragment to display based on the order
        // in the SectionPagerAdapter's getItem method
        // 2 =  CheckinFragment
        int view_page = intent.getIntExtra("viewpager_position", 2);
        // Render the MainActivity's layout which houses the viewpager layout
        setContentView(R.layout.activity_main);

        // Instantiate the viewModel using the PatientDetails class
        // This is used to share the same data across all vragments of the viewpager
        patientModel = ViewModelProviders.of(this).get(PatientDetails.class);

        // Below code generated by choosing "Tabbed Activity" when creating the project initially
        // SectionPageAdapter, ViewPager and TabLayout handling displaying the Fragments, moving
        // from one Fragment to the other and displaying the Tabbed Layout
        SectionsPagerAdapter sectionsPagerAdapter = new SectionsPagerAdapter(this,
                getSupportFragmentManager());
        ViewPager viewPager = findViewById(R.id.view_pager);
        viewPager.setAdapter(sectionsPagerAdapter);
        viewPager.setCurrentItem(view_page);
        TabLayout tabs = findViewById(R.id.tabs);
        tabs.setupWithViewPager(viewPager);

        // Read the user's saved encrypted file contents from the App storage
        String encrypted_data = encryption.basicRead(MainActivity.this, DATA_FILENAME);
        // Decrypt the data retrieved from the file using the Symmetric key from the Android
        // Keystore
        String json_data = encryption.decryptSymmetrically(encrypted_data, SYMMETRIC_ALIAS);

        // @troubleshooting
        //String json_data = null;

        // Declare a new PatientDetails instance
        PatientDetails p;
        // Check if the decrypted data is null (this happens if the data is empty/
        // or there was an error in decrypting the data
        if(json_data != null) {
            // Reference: https://mkyong.com/java/how-do-convert-java-object-to-from-json-format-gson-api/
            // Use the GSON class to parse the decrypted data from JSON String
            // to a new PatientDetails instance
            p = gson.fromJson(json_data, PatientDetails.class);
        } else {
            // Otherwise instantiate an empty PatientDetails instance
            p = new PatientDetails();
        }

        // Use the PatientDetails' class' methods to load the decryted and converted data
        // to the viewModel
        patientModel.setPersonalDetails(
                p.getName(), p.getEmail(), p.getDateOfBirth(), p.getAddress(), p.getAddress2(),
                p.getCity(),p.getPostCode(),p.getPPSNumber(),p.getInsurance(), p.getCurrentSessionID()
        );
        patientModel.setMedicalDetails(
                p.getBloodType(), p.getAllergies(), p.getTubercolosis(), p.getDiabetes(),
                p.getHeartCondition(), p.getGloucoma(), p.getEpilepsy(), p.getDrugAlcoholAbuse(),
                p.getSmoker(), p.getCancer(), p.getOtherConditions(), p.getMedications(),
                p.getHeight(), p.getWeight(), p.getRegisteredGP()
        );
        patientModel.setPatientSessions(p.patientSessions);

    }

    // Reference: https://developer.android.com/guide/topics/ui/menus#options-menu
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        /* Method to display an options menu
         * @param Menu menu The menu that should be displayed
         * @return boolean
         */

        // Render options menu
        MenuInflater inflater = getMenuInflater();
        inflater.inflate(R.menu.settings_menu, menu);
        return true;
    }

    // Reference: https://developer.android.com/guide/topics/ui/menus#RespondingOptionsMenu
    @Override
        public boolean onOptionsItemSelected(MenuItem item) {
        /* Method to handle the functionality of the selected options menu item
         * @param MenuItem item The selected options menu item
         * @return boolean
         */

        // Switch conditional statement to handle item selection
        switch (item.getItemId()) {
            // If the option "Clear Data" is selected
            case R.id.cleanse_data:
                // Display a confirmation dialog first to make sure
                // the user wants to delete the data
                // Reference: https://stackoverflow.com/a/5127506
                new AlertDialog.Builder(this)
                        .setTitle("Clear Data")
                        .setMessage("Do you really want to clear all data?")
                        .setIcon(android.R.drawable.ic_dialog_alert)
                        .setPositiveButton(android.R.string.yes, new DialogInterface.OnClickListener() {
                            public void onClick(DialogInterface dialog, int whichButton) {
                                // When the dialog is confirmed
                                // Create a new empty PatientDetails instance
                                // and save it in the local storage file
                                PatientDetails clean_patient = new PatientDetails();
                                encryption.saveData(clean_patient, SYMMETRIC_ALIAS,
                                        getApplicationContext(), DATA_FILENAME);
                                // Close the menu and restart the activity
                                finish();
                                startActivity(getIntent());
                            }})
                        .setNegativeButton(android.R.string.no, null).show();
                return true;
            case R.id.change_code:
                // If the option "New Verification Code" is selected
                // Redirect to the CreateCodeActivity
                Intent codeIntent = new Intent(this, CreateCodeActivity.class);
                startActivity(codeIntent);
                return true;
            case R.id.logout:
                // If the option "Logout" is selected
                // Logout
                mAuth.signOut();
                // And redirect to the LoginActivity
                Intent loginActivity = new Intent(getApplicationContext(), LoginActivity.class);
                startActivity(loginActivity);;
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }
}